# Generated by Django 2.1.1 on 2018-09-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymmdd', models.CharField(max_length=10)),
                ('hhmmss', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('val', models.IntegerField(default=0)),
                ('pubdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnt', models.CharField(max_length=200)),
                ('yymmdd', models.CharField(max_length=200)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
    ]
